shell = "zsh"

[plugins]

[plugins.enhancd]
github = "b4b4r07/enhancd"

[plugins.LS_COLORS]
github = "trapd00r/LS_COLORS"

[plugins.lazygit]
github = "jesseduffield/lazygit"

[plugins.lazydocker]
github = "jesseduffield/lazydocker"

[plugins.zoxide]
github = "ajeetdsouza/zoxide"

[plugins.fzf]
github = "junegunn/fzf"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.fzf-fasd]
github = "wookayin/fzf-fasd"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.history-search-multi-word]
github = "psprint/history-search-multi-word"

[plugins.zsh-256color]
github = "chrissicool/zsh-256color"

[plugins.zsh-async]
github = "mafredri/zsh-async"

[plugins.auto-color-ls]
github = "mafredri/auto-color-ls"

[plugins.zsh-bash]
github = "chrissicool/zsh-bash"

[plugins.yadm-zsh]
github = "juanrgon/yadm-zsh"

[plugins.fast-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"

[plugins.zsh-history-search-multi-word]
github = "zsh-users/zsh-history-substring-search"