shell = "zsh"

[plugins]

[plugins.enhancd]
github = "b4b4r07/enhancd"

[plugins.fzf]
github = "junegunn/fzf"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.fzf-fasd]
github = "wookayin/fzf-fasd"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.history-search-multi-word]
github = "psprint/history-search-multi-word"

[plugins.zsh-256color]
github = "chrissicool/zsh-256color"

[plugins.zsh-async]
github = "mafredri/zsh-async"

[plugins.auto-color-ls]
github = "mafredri/auto-color-ls"

[plugins.zsh-bash]
github = "chrissicool/zsh-bash"

[plugins.yadm-zsh]
github = "juanrgon/yadm-zsh"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.zsh-history-search-multi-word]
github = "zsh-users/zsh-history-substring-search"

zsh-git zsh-doc-git spaceship-prompt-git zsh-you-should-use gitstatus pacac-zsh-completions zsh-directory-history-git git-completion prll cod-git zsh-abbr zsh-autopair pmy-git zsh-system-clipboard-git zsh-fzy-git zsh-load nvmrc fzf-tab-completion-git histdb-rs neovim-coc-zsh-git zsh-sudo-git zsh-history-search-multi-word-git

